server:
  port: 10000

eureka:
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 30  # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: 117.48.214.169
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/